### ISSUE TITLE
Remove and Restore Default Settings (High Sierra)

### ISSUE THREAD

**Issue by ppkantorski** [w0lfschild/DarkBoot#100]
Hi, I've looked through you're proposed methods of restoring the default settings but for some reason none of the solutions seem to do the trick.  I wanted my lockscreen and logon image to return to normal so that by setting the background image through right clicking in Finder and setting as background, it thereby changes my lockscreen and logon image as well.  However no matter what I do the image for these screens seems to only be able to be set by DarkBoot.

How can I remove DarkBoot and restore the default settings so that I can change my image the way macOS intends?

**Comment by fjdr** [comment]
I have the same trouble.

**Comment by fjdr** [comment]
Try resetting the ePRAM. I think this resolve the issue

**Comment by w0lfschild** [comment]
Yeah, hard to say. Maybe just delete the files on disk and let MacOS try to repopulate them.
