### ISSUE TITLE
LoginWindow process Crash

### ISSUE THREAD

**Issue by fjdr** [w0lfschild/DarkBoot#102]
Aleatory the LoginWindow crash.
Special keys disabled ( sound and display bright irresponsible )
No restart, shutdown, or About this Mac.

At this time give me an error with Sandbox:

error	23:20:09.476979 -0300	sandboxd	Sandbox: osxinj(1234) System Policy: allow mach-priv-task-port loginwindow(110)

**Comment by fjdr** [comment]
Hello:
I review this and DarkBoot is not responsible.
The problem is made by GFXstatus

**Comment by UnderEu** [comment]
> Hello:
> I review this and DarkBoot is not responsible.
> The problem is made by GFXstatus

Man, I'm having the exact same issue right now on my machine - since I upgraded to 10.14.4 (18E226) last month.
I have both **DarkBoot** and **gfxCardStatus** installed.

I get here because my /var/log/system.log is logging the following message every 30s since boot-up (which is one of my suspects):
`May 12 22:57:27 Unders-Macbook com.apple.xpc.launchd[1] (com.w0lf.dblockinjector): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
`

@fjdr Were you able to solve this or, at least, apply a workaround for it? Really... this issue is driving me crazy every single day!

**Comment by fjdr** [comment]
Sorry

I can’t help you because I do not know what’s is your trouble. 

Regards

Atentamente


Francisco Javier Dominguez Rogers / ARQvision Arquitectura BIM Sustentable




url: http://www.arqvision.cl/
email: fjdr@arqvision.cl ●  mobile: +56 (9) 9 5010-3283

**Comment by UnderEu** [comment]
> Sorry I can’t help you because I do not know what’s is your trouble. Regards Atentamente Francisco Javier Dominguez Rogers / ARQvision Arquitectura BIM Sustentable url: http://www.arqvision.cl/ email: fjdr@arqvision.cl ● mobile: +56 (9) 9 5010-3283
> […](#)
> On May 12, 2019, at 10:07 PM, Anderson Silva ***@***.***> wrote: Hello: I review this and DarkBoot is not responsible. The problem is made by GFXstatus Man, I'm having the exact same issue right now on my machine - since I upgraded to 10.14.4 (18E226) last month. I have both DarkBoot and gfxCardStatus installed. I get here because my /var/log/system.log is logging the following message every 30s since boot-up (which is one of my suspects): May 12 22:57:27 Unders-Macbook com.apple.xpc.launchd[1] (com.w0lf.dblockinjector): Service only ran for 0 seconds. Pushing respawn out by 10 seconds. @fjdr Were you able to solve this or, at least, apply a workaround for it? Really... this issue is driving me crazy every single day! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

How did you conclude gfxCardStatus was your issue?

**Comment by fjdr** [comment]
Dear Mr.

My MBP 17 is running High Sierra. Then can’t know what happens in Mojabe

Regards

Cordialmente


Francisco Javier Dominguez Rogers
+56 9 5010 3283

**Comment by UnderEu** [comment]
> Dear Mr. My MBP 17 is running High Sierra. Then can’t know what happens in Mojabe Regards Cordialmente Francisco Javier Dominguez Rogers +56 9 5010 3283


How did you figure that out, back in the day, that gfxCardStatus was an issue for you? THAT'S what I want to know! Forget my current issue, I need to know yours and what you've done.
