### ISSUE TITLE
Image is Cut in Lock Screen

### ISSUE THREAD

**Issue by fjdr** [w0lfschild/DarkBoot#103]
Hello:

Why the wall paper image is cut in the left and right ends?

![lwscreenshot 2018-10-30 at 8 33 19 pm](https://user-images.githubusercontent.com/20794545/47757204-17546200-dc84-11e8-9e4e-82326a15b6fc.png)

my email is fjdr@icloud.com

Regards

**Comment by w0lfschild** [comment]
Not sure, probably has to do with the size of the image you used?
