### ISSUE TITLE
GitHub isn't letting me download it, because the repository had been disabled. 

### ISSUE THREAD

**Issue by CobreDev** [w0lfschild/DarkBoot#105]
Whenever I go to download it, it tells me that:

 "This repository has been disabled.
Access to this repository has been disabled by GitHub staff. Contact support to restore access to this repository."  

Is there any other place that I can download this?

Thanks!

**Comment by TjPk** [comment]
[DarkBoot-master.zip](https://github.com/w0lfschild/DarkBoot/files/2887135/DarkBoot-master.zip)
here you go :)

**Comment by w0lfschild** [comment]
Closing as this was fixed a long while ago.
