### ISSUE TITLE
Dark boot causes dock to crash when I mouse over it (I believe)

### ISSUE THREAD

**Issue by TjPk** [w0lfschild/DarkBoot#106]
I'm a complete n00b at this, so I updated my dark boot a while ago, and I just now got around to writing this. so basically, as the title suggests, the dock crashes, dissapears, and my wallpaper goes away whenever I mouse over my dock. this problem persists against restarts. as I don't need dark boot anymore, is there a way to uninstall it? the dock process crashes. this (obviously) renders my dock unusable. I'm not sure it's dark boot however. what's the dark boot helper process called? I could try manually killing it in activity monitor.

**Comment by w0lfschild** [comment]
Most likely cDock. The DarkBoot app does nothing with the dock.
