### ISSUE TITLE
DarkBoot causes total dark mode over whole system

### ISSUE THREAD

**Issue by raywongw** [w0lfschild/DarkBoot#107]
![screen shot 2019-02-23 at 8 10 54 pm](https://user-images.githubusercontent.com/47918271/53286291-25843c00-37a7-11e9-85b4-ac668629ac66.png)
Hmm,I applied the settings in the photo, with custom login screen and lock screen applied ,I ended up with a surprise on system-wide dark mode(kind of,i think), which makes me messed up in finder as the words are not easily seen. I have tried using[defaults write -g NSWindowDarkChocolate -bool FALSE] in terminal in order to revert back to light mode and it makes no success attempt in fixing the issue.Huge thanks if anyone can fix my issue.

System used for testing: MacBook Pro Late 2011(13-inch model,Core i5 version)
macOS currently on:macOS High Sierra(10.13.6)with Security update 2019-001

**Comment by w0lfschild** [comment]
This looks like maybe a plugin like [DrDark](https://github.com/w0lfschild/DoctorDark), you sure you're not using any of my other plugins/apps?
