### ISSUE TITLE
Cannot boot after running Dark Boot

### ISSUE THREAD

**Issue by kennett420** [w0lfschild/DarkBoot#11]
I installed Dark Boot 3.1 on my Yosemite disk (10.10.3) and I set the software to show a grey screen. My Yosemite disk does not show up when I restart holding the option key down, only the 10.10.3 recovery partition shows up. I would like to know how to uninstall this software.

**Comment by audioslave74** [comment]
You must copy your old boot.efi on /System/Library/CoreServices/boot.efi and delete stock_boot.efi

If you don't have backup of your old boot.efi You have just messed up!

**Comment by w0lfschild** [comment]
@audioslave74 stock_boot.efi is a backup of the stock boot.efi

Boot to recovery.
Open terminal.

```
mv /Volumes/<boot volume here>/System/Library/CoreServices/boot.efi /Volumes/<boot volume here>/System/Library/CoreServices/boot.efi.bak
mv /Volumes/<boot volume here>/System/Library/CoreServices/boot_stock.efi /Volumes/<boot volume here>/System/Library/CoreServices/boot.efi
```

Obviously replacing <boot volume here> with your actual boot volume name like Mackintosh HD or whatever.

Reboot.
