### ISSUE TITLE
Boot image option grayed out

### ISSUE THREAD

**Issue by Flipp3rrr** [w0lfschild/DarkBoot#111]
I can't change the boot logo on version 6.1.0 (135) on macOS 10.14.6, is this intended? I would love to change the logo.
![Screenshot 2019-11-09 at 17 39 08](https://user-images.githubusercontent.com/33151653/68531908-d9b6fa00-0317-11ea-978c-e996b8e0af38.png)

**Comment by w0lfschild** [comment]
It is intentionally greyed out. I'm gonna refer you to this issue:

https://github.com/w0lfschild/DarkBoot/issues/92
