### ISSUE TITLE
Image gets overwritten / App resets

### ISSUE THREAD

**Issue by team-orangeBlue** [w0lfschild/DarkBoot#116]
If I change the image (even the samples) it doesn't work, the image is still white, and when I open the app again, I see the default logo for some reason, even if I press "Apply changes".
It probably looks like that the app does not save the changes.
If this can help fixing the issue, I'm using macOS 10.14.6.

**Comment by w0lfschild** [comment]
What image? Boot image hasn't worked for years and if you're using a recent version that option shouldn't even be visible.

https://github.com/w0lfschild/DarkBoot/issues/92
