### ISSUE TITLE
Stuck in boot loop

### ISSUE THREAD

**Issue by c-waller** [w0lfschild/DarkBoot#118]
I’m assuming dark boot is causing this. Frequently when I’d use the program my mac would switch from the black boot screen to the white one simultaneously while booting up. I was concerned about this but my computer still booted anyway. 

Recently I tried to restart my computer and it went through the black boot screen, almost finished, then switched to the white one. The computer now restarts constantly when trying to boot up into the operating system and refuses to get past the boot screen. 

I can still enter safe mode so I was wondering if there was a way I could possibly disable it from terminal without having to wipe my install.

**Comment by w0lfschild** [comment]
Darkboot only sets nvram variables that already exist. Likely your computer is having it's own separate issues.
