### ISSUE TITLE
Bootmenu fonts unreadable when background is black. Change fonts color?

### ISSUE THREAD

**Issue by Ando02** [w0lfschild/DarkBoot#126]
![Imagepipe_4](https://user-images.githubusercontent.com/18426732/103352699-3c80cd00-4aa7-11eb-88ac-a9ca786b25ed.jpg)

I´ve got an old imac mid 2007 (20''). I´ve updated its CPU and used some "Patch Scritps". So I could update to Mojave. Everything works well... 😀👍  (Well, except imovie... preview window stays black)
The "Dark Boot" works great, too! Thank you!!!

But: When I boot that old imac with the ALT key pressed (bootmenu) I cant read anything under the HDD, USB or DVD Icons. Maybe it is a black font on a black background?

Can I change the font color to white?

**Comment by w0lfschild** [comment]
Yup it's Black Text on Black background. Sadly nothing can be done about that.
