### ISSUE TITLE
Unable to select Boot image option in 

### ISSUE THREAD

**Issue by samrth012** [w0lfschild/DarkBoot#129]
## Bug Report

**Current Behavior**
Unable to select boot image tab

**Expected behavior/code**
I should have option to select 

**Screenshots**

**Environment**
- OS version: 11.2.3

The option is greyed out and I am unable to select it.

![Screenshot 2021-04-24 at 10 57 29 AM](https://user-images.githubusercontent.com/63335952/115948422-ee775580-a4eb-11eb-8102-9c7e7cdccc14.png)

**Comment by w0lfschild** [comment]
Custom boot images aren't supported by Apple anymore.
