### ISSUE TITLE
Run Shell Script dialog

### ISSUE THREAD

**Issue by Rjdiseno** [w0lfschild/DarkBoot#13]
Hi,

I'm running DarkBoot on my iMac 27", Yosemite 10.10.3 and it seems to run ok but when all is finished and loaded I get this message (see image).  

Rob.

![screen shot 2015-06-17 at 8 36 48 am](https://cloud.githubusercontent.com/assets/12937153/8208581/f19cb8ae-14cd-11e5-94b8-517c5539bb7b.png)

**Comment by w0lfschild** [comment]
This should be fixed in the latest update.
