### ISSUE TITLE
re: Boot Image in 10.14.6 on MBP 7,1

### ISSUE THREAD

**Issue by TheFirstFarmerBob** [w0lfschild/DarkBoot#132]
I have changed the Boot Image on my cMP 3,1 and love it. But that is the only option that is not available in v7.0.1 on my MBP 7,1 and that's about all I want from it.

Any assistance will be greatly appreciated.

Thank you . . . 
. . . @TheFirstFarmerBob

**Comment by w0lfschild** [comment]
Boot image is no longer an option and hasn't been for a few years. The default boot does not accept custom images.
