### ISSUE TITLE
Boot screen color turns back to original color

### ISSUE THREAD

**Issue by aqua96** [w0lfschild/DarkBoot#134]
I dont know if it's really a bug, but when applying the grey boot screen, when starting up my mac it has the grey screen for a few seconds and then it turns back to black (original color) before going to login screen.
I have a 2016 macbook pro 13-inch, tested the app on macOS Sierra, but i think the same thing applies for other macOS too.

**Comment by w0lfschild** [comment]
Unfortunately nothing can be done about that. It's just how the boot process works.
