### ISSUE TITLE
Admini password

### ISSUE THREAD

**Issue by Tom11w** [w0lfschild/DarkBoot#14]
I am having a Problem after I have started the main program and select my desired Boot Color. I press Apply and It asks for a password. I give it one and then it never accepts anything and says that the password that I entered was incorrect and then just disappears after 5 failed attempts. I have tried restarting my computer and the program with nothing changing. I have tried my password (I'm a admin) and the root users password and the master password and nothing seems to be working. Please help. Thank you -Tom

**Comment by w0lfschild** [comment]
Dunno honestly. It needs to be the sudo password.

**Comment by w0lfschild** [comment]
Okay actually now I do know.

This only works on an Admin account. Won't run on a standard account unless you give it sudo access.

**Comment by Tom11w** [comment]
I have made a youtube video to try and show the problem a little better at here https://www.youtube.com/watch?v=PvCHLwukXkY
I am on a MacBook Pro (13-inch, Late 2011) with a 2.8 GHz Intel Core i7 and 8 GB 1333 MHz DDR3 and Intel HD Graphics 3000 512 MB Running OS X 10.10.4 (14E46) and I am using Dark Boot Version 3.4

**Comment by w0lfschild** [comment]
Yes like I posted above. It's got to be run on an admin account or a standard account that's been given sudo access ( http://osxdaily.com/2014/02/06/add-user-sudoers-file-mac/ ).

Just open terminal and try typing

```
sudo echo hello
```

If that works then so will Dark Boot

**Comment by Tom11w** [comment]
Thank You so much for replaying. It turned out to be a problem that my mac had with the sudo command. When tried to use the sudo command i would get "sudo: can't open /private/etc/sudoers: Permission denied  |  sudo: no valid sudoers sources found, quitting" but by using "su" then using "chmod g+x /" Fixed the problem. Used your app and rebooted 2 times and it worked. But now I'm getting a alert window that says The action “Run Shell Script” encountered an error. Check the actionʼs properties and try running the workflow again. Dose not seem to be affecting anything though so Im happy. Thank you for your time and thank you for replaying to my question. :)
