### ISSUE TITLE
Latest El Capitan public beta failed boot

### ISSUE THREAD

**Issue by eqxovld** [w0lfschild/DarkBoot#15]
Shows Circle with slash (see image below) when i try to boot

![image](https://cloud.githubusercontent.com/assets/9395578/8646371/29fabf30-2904-11e5-99e8-9e7415674756.png)

**Comment by w0lfschild** [comment]
See here: https://github.com/w0lfschild/DarkBoot/issues/11#issuecomment-120082539

I'm guessing you're using a newer mac?

**Comment by eqxovld** [comment]
i am using a mid-2012 macbook pro 13", i used the image from the apple website for reference the background is actually greyish with a white circle with slash

**Comment by MacKeeper28** [comment]
I had this same problem, and when I tried to recover from it, Terminal in recovery mode said that sudo wasn't a command.  I finally booted into another drive and tried to revert the stock_boot.efi.  I had rootless disabled and it still wouldn't let me.  Then when I tried to reboot back into my old system, it magically worked.  Dark boot isn't enabled though.  The error it gave the first time was that there was no kernel cache.

**Comment by batt3r3d** [comment]
Same here .. rootless is disabled (recovery mode) but after booting normal the status is enabled.
I tried to revert the boot.efi but the operation is not permitted (recovery mode). The strange behavior 
is that every 2nd boot the screen is black but rootless is nevertheless active. I would like back to default. Any ideas? ..

**Comment by MacKeeper28** [comment]
Disable rootless from recovery and in recovery, cd to the boot.efi folder and do chflags nouchg./boot.efi and then you can restore the old one.  Make sure you do chflags uchg on the old boot.efi once you've renamed it.

**Comment by batt3r3d** [comment]
@MacKeeper28 

Thank you, solved!

**Comment by MacKeeper28** [comment]
But the program still doesn't work on this MacBook model and the dev hasn't responded for a while now.  :/
