### ISSUE TITLE
Mavericks

### ISSUE THREAD

**Issue by asoksevil** [w0lfschild/DarkBoot#16]
Does it work on Mavericks? It says so on the website but once you download the installer none of that is mentioned.

**Comment by w0lfschild** [comment]
No idea.

**Comment by asoksevil** [comment]
It used to be on this page: http://w0lfschild.github.io/pages/dboot.html

But it has recently changed from Mavericks to Yosemite.

**Comment by w0lfschild** [comment]
Well did you try it out?

**Comment by asoksevil** [comment]
Apologies for the late reply.

No, I didn´t as I felt it was going to screw up my laptop...

**Comment by w0lfschild** [comment]
Well this does indeed work on Mavericks. Should honestly work on any version of OS X as long as the app can open.

**Comment by asoksevil** [comment]
@w0lfschild 

So I downloaded the latest version available today (3.5) and applied the "black boot color" but didn´t work at all after rebooting. It was still showing the traditional grey one.

I am running OS X 10.9.5 13F1112 on a 2010 MacBook Air.

**Comment by w0lfschild** [comment]
Did you reboot twice?

**Comment by asoksevil** [comment]
That did it, working now.

I am not sure if it´s supposed to do this but after finishing loading, it flickers to the grey one and then to another lighter grey. It might be the way Mavericks is set up so I am guessing this looks better on Yosemite.

**Comment by asoksevil** [comment]
Just an update on Mavericks compatibility.

It doesn't show the loading bar and the main website no longer lists Mavericks as supported.
