### ISSUE TITLE
Hackintosh

### ISSUE THREAD

**Issue by Flaviocdac** [w0lfschild/DarkBoot#17]
Hi,
On my hackintosh (Yosemite 10.10.5) it doesn't work. I tried to do this a lot times. I followed all the steps.

**Comment by w0lfschild** [comment]
Pretty sure hackintosh use their own boot file. I will not be making any changes to Dark Boot related to the efi at this point.

Here's a guide that might help you:
http://www.tonymacx86.com/customization/114229-guide-how-definitely-get-grey-apple-boot-up-black-stretched-boots-no-more-hex-editing.html
