### ISSUE TITLE
Yosemite doesn`t boot

### ISSUE THREAD

**Issue by Infectum** [w0lfschild/DarkBoot#18]
After use this app yosemite doesn't boot, system event can't see OS X partition. But i can access to partition under windows. How i can to fox os x boot?

**Comment by w0lfschild** [comment]
Boot into your recovery partition (boot holding Command + R)
• Open Terminal
• Enter the following commands:

```
    cd /Volumes/<name of boot partition>/System/Library/CoreServices
    mv ./boot.efi ./boot.efi.bak
    mv ./boot_stock.efi ./boot.efi
    chmod 644 ./boot.efi
    chown root:wheel ./boot.efi
    chflags uchg ./boot.efi
```

• Reboot

**Comment by Infectum** [comment]
When i enter to recovery, its starts to download something, its never happened before. Did recovery partition is also broken?

**Comment by w0lfschild** [comment]
Nope Dark Boot doesn't do anything to your recovery partition.

**Comment by Infectum** [comment]
If i wait to download finish, that will be broke my os x partition?

**Comment by w0lfschild** [comment]
I don't know what you're talking about... You probably didn't have a recovery partition so it's being downloaded. If you let it finish it will finish booting into recovery mode.

**Comment by Infectum** [comment]
ok, thanks, i will try

**Comment by Infectum** [comment]
I can't, there no some file 
![2](https://cloud.githubusercontent.com/assets/13951971/9454797/12788364-4ac5-11e5-9b0f-55beecde2fd8.jpg)

**Comment by w0lfschild** [comment]
I guess you have to go to: 

`cd /Volumes/<Name of your boot partition>/System/Library/CoreServices`

**Comment by Infectum** [comment]
Nothing... Its impossible to fix. I didnt have "./boot.efi.bak"... Can i do this under the windows?

**Comment by Infectum** [comment]
If you give me this files, i can to put it in windows. My iMac is 21.5"  late 2011

**Comment by w0lfschild** [comment]
<Name of your boot partition> should be replaced by your actual boot volume

Try using `ls -l /Volumes/` if you don't know what your boot volume name is

I also never said you should have boot.efi.bak you're replacing boot.efi with boot_stock.efi which is the backup that Dark Boot makes.

**Comment by Infectum** [comment]
Sorry, but i tried everything, but nothing. I think, that Dark Boot don't created backup file. There aro just that boot.efi files 
![boot efi](https://cloud.githubusercontent.com/assets/13951971/9507610/c05e3754-4c4f-11e5-97d3-79b48c2077ed.jpg)

**Comment by Infectum** [comment]
So, its possible to fix this?
