### ISSUE TITLE
Error macbook pro 13" 8.1

### ISSUE THREAD

**Issue by Laidbak83** [w0lfschild/DarkBoot#2]
It doesn't work yosemite 10.10.1

multiple try ....

help me ==)

Thx

**Comment by w0lfschild** [comment]
What exactly did you do?

After you run the app open terminal and type:

```
    ttt=$(bless --info | grep "Blessed System File"); ttt='/'${ttt#*/}; echo "$ttt";
```

What does it print out?

**Comment by Laidbak83** [comment]
I launch app n reboot twice but Notting ;(

Thx for ur answer

**Comment by w0lfschild** [comment]
You didn't answer the second part of the question.

**Comment by Laidbak83** [comment]
i'm french ...

i've not type this line in terminal because it's not say in description ^^

**Comment by Laidbak83** [comment]
i try this now i've to type this line after or before i type my password in app ?

**Comment by w0lfschild** [comment]
After.

**Comment by Laidbak83** [comment]
ok i'm retry now

**Comment by Laidbak83** [comment]
MacBook-Pro-de-Bastien:~ Bastien$ ttt=$(bless --info | grep "Blessed System File"); ttt='/'${ttt#*/}; echo "$ttt";
/
MacBook-Pro-de-Bastien:~ Bastien$

**Comment by Laidbak83** [comment]
only

**Comment by Laidbak83** [comment]
reboot twice but nothing change :(

**Comment by w0lfschild** [comment]
Okay. Thanks and what does this print out? (you don't need to run the app again)

```
ttt=$(bless --info | grep "efi"); ttt='/'${ttt#*/}; echo "$ttt";
```

also what does just this print out?

```
bless --info
```

**Comment by Laidbak83** [comment]
Last login: Tue Jan 13 22:17:13 on console
MacBook-Pro-de-Bastien:~ Bastien$ ttt=$(bless --info | grep "efi"); ttt='/'${ttt#*/}; echo "$ttt";
/
MacBook-Pro-de-Bastien:~ Bastien$ bless --info
MacBook-Pro-de-Bastien:~ Bastien$

**Comment by w0lfschild** [comment]
Interesting I'm going to assume this means you don't even have the bless command... maybe it's not standard.

Last thing to check what does this output?

```
man bless
```

**Comment by Laidbak83** [comment]
BLESS(8)                  BSD System Manager's Manual                 BLESS(8)

NAME
     bless -- set volume bootability and startup disk options

SYNOPSIS
     bless --help

```
 bless --folder directory [--file file] [--bootinfo [file]]
       [--bootefi [file]] [--label name | --labelfile file] [--setBoot]
       [--openfolder directory] [--nextonly] [--shortform] [--legacy]
       [--legacydrivehint device] [--options string] [--quiet | --verbose]

 bless --mount directory [--file file] [--setBoot] [--nextonly]
       [--shortform] [--legacy] [--legacydrivehint device]
       [--options string] [--quiet | --verbose]

 bless --device device [--label name | --labelfile file]
       [--startupfile file] [--setBoot] [--nextonly] [--shortform]
       [--legacy] [--legacydrivehint device] [--options string]
       [--quiet | --verbose]
```

:

**Comment by Laidbak83** [comment]
do u want my team viewer ID ?

**Comment by w0lfschild** [comment]
Okay... Then your system does have bless so. Let's try this.

```
ls -l /dboot
```

**Comment by Laidbak83** [comment]
MacBook-Pro-de-Bastien:~ Bastien$ ls -l /dboot
total 2288
-rw-r--r--@ 1 root     admin  583736 13 jan 22:11 black_boot.efi
-rw-r--r--  1 Bastien  wheel  583736 13 jan 22:11 gray_boot.efi
MacBook-Pro-de-Bastien:~ Bastien$

**Comment by w0lfschild** [comment]
Okay then try this:

```
cd /dboot; sudo bless --folder . --file black_boot.efi --labelfile .disk_label; bless --info
```

**Comment by Laidbak83** [comment]
MacBook-Pro-de-Bastien:~ Bastien$ cd /dboot; sudo bless --folder . --file black_boot.efi --labelfile .disk_label; bless --info
Password:
MacBook-Pro-de-Bastien:dboot Bastien$

**Comment by w0lfschild** [comment]
I honestly am not sure at this point... Everything looks right but for some reason bless doesn't seem to be doing anything.

**Comment by Laidbak83** [comment]
lol i don't know you want my team viewer id ?

**Comment by w0lfschild** [comment]
Does adding verbose to bless print anything:

```
cd /dboot; sudo bless --verbose --folder . --file black_boot.efi --labelfile .disk_label
```

**Comment by Laidbak83** [comment]
Last login: Tue Jan 13 22:35:33 on ttys000
MacBook-Pro-de-Bastien:~ Bastien$ cd /dboot; sudo bless --verbose --folder . --file black_boot.efi --labelfile .disk_label
Password:
EFI found at IODeviceTree:/efi
Mount point for . is /
Common mount point of '.' and '' is /
No BootX creation requested
No boot.efi creation requested
Got directory ID of 824687 for .
Got file ID of 824688 for black_boot.efi
finderinfo[0] = 824687
finderinfo[1] = 824688
finderinfo[2] = 0
finderinfo[3] = 0
finderinfo[5] = 824687
Scale 1 label data is valid: YES
Putting scale 1 label bitmap in ./.disk_label
Deleting old ./.disk_label
Opened dest at ./.disk_label for writing
0x00001000 bytes preallocated for ./.disk_label

Type/creator set to tbxj/chrp for ./.disk_label
Scale 1 label written
Invisibility set for ./.disk_label

**Comment by w0lfschild** [comment]
Well I dunno. Looks like it worked. Try restarting twice. Otherwise I'd try using the previous release.

**Comment by Laidbak83** [comment]
nothing .... snif

**Comment by Laidbak83** [comment]
i'll try de older release ?

**Comment by w0lfschild** [comment]
Yeah go for it.

**Comment by Laidbak83** [comment]
where is she ?^^

**Comment by Laidbak83** [comment]
i can't find it :(

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/releases

**Comment by Laidbak83** [comment]
thx !!!!

it works with old release but only if switch of but no if i reboot 

thx a lot
