### ISSUE TITLE
No DarkBoot after Verbose is done

### ISSUE THREAD

**Issue by ghost** [w0lfschild/DarkBoot#20]
So i noticed that when I have Verbose boot enabled ( sudo nvram boot-args=”-v” ) the loading screen after the scrolling text is still the default... But the screen before the tone is black it doesn't go default until after the scrolling text stops 

I'm on a 13-Inch Late 2011 MacBook Pro running OS X Yosemite 10.10.5

**Comment by JayBrown** [comment]
Interesting: in my case (10.11.4) it's the default grey screen before start of verbose boot, and after verbose boot it's the standard grey screen with dark grey icon; only the boot progress bar has turned white.

**Comment by JayBrown** [comment]
This bug has been squashed with the newest update: dark before verbose works, dark after verbose works too (10.11.4). Haven't checked substitute boot logo yet. But as for the standard dark boot, it's working here. So you can close the issue.
