### ISSUE TITLE
Rootless enable

### ISSUE THREAD

**Issue by johnntyparafango** [w0lfschild/DarkBoot#23]
Hi w0lfshild,
I tried to use your app to enable dark boot but it says that rootless its enabled and to execute the "scrutil disable" command in the recovery partition. Unfortunately terminal responds with command not found. I also tried to disable rootless with "sudo nvram boot-args="rootless=0" and a reboot. The terminal seems to accept it but yours app still says the same thing. I also tried with rootlessToggler app but same result,

If you have some suggestions I will appreciate. Thank you

**Comment by w0lfschild** [comment]
Try using

`/Volumes/*/usr/bin/csrutil disable` instead of just `csrutil disable`

rootlessToggler does nothing and only worked for a few select beta builds.

**Comment by GodsBlindSpot** [comment]
johnntyparafango – the command is "csrutil disable" not "scrutil disable." There is a typo in the DarkBoot app.
