### ISSUE TITLE
El Capitan System Integrity Protection (SIP) Issues

### ISSUE THREAD

**Issue by RushHour2k5** [w0lfschild/DarkBoot#26]
After running your program and enabling Dark Boot on a MacBookPro 7,1 and MacBookPro8,1 El Capitan no longer recognizes when System Integrity Protection (SIP) is disabled from the OS X Recovery partition. Manually booting to the recovery partition and restoring the boot_stock.efi file manually does not resolve the issue. When booting to OS X Recovery and running 'csrutil status' from the terminal it reports disabled however when booting to the normal El Capitan install it shows enabled. This issue did not occur until the boot.efi was replaced by your program. The only way to recover this issue is to re-run 'Install OS X El Capitan.app' from within El Capitan as attempts to clear the NVRAM and reset the 'csrutil disable' parameter does not resolve it.

**Comment by MrRod** [comment]
I'm having the same issue

**Comment by DimitriDokuchaev** [comment]
Came to report that exact issue it borks SIP completely, had to restore yesterday, and now to troubleshoot i installed it, it borked it again, so there you go a bug, that completely brakes SIP.  

Specs Macbook pro 4,1 (early 2008)

**Comment by georgeel** [comment]
Same on my Mac Pro 2009 (4,1)!
Plus, Dark boot turned back to light with no intervention, no upgrade at all.

**Comment by RushHour2k5** [comment]
Why is this closed with no response from the developer on how to fix the issue?

**Comment by w0lfschild** [comment]
@pilot76103 

Dark Boot no longer modifies the efi file so this should no longer be a problem.
