### ISSUE TITLE
DARK BOOT DECEMBER 2015 EL CAPITAN 10.11.2

### ISSUE THREAD

**Issue by bigshaw3** [w0lfschild/DarkBoot#31]
There has been a new OSX update which reverted my computer back to white boot screen. Can't wait for you guys next update to DarkBoot to fix this, you guys are awesome for figuring this hack out btw... Apple is stupid for leaving some Macs with the white boot screen... The only Macs that should still have that boot screen is the white Macbooks and Macs because it actually matches! All silver + black aluminum Macs should have dark boot by default because it matches and compliments the hardware beautifully. Well, thats why we have awesome guys like you guys who help the community out with the little things like that. Hope you guys can include the new Yosemite/ El Capitan dead battery boot logo with the next update aswell. Thanks you guys are the best

**Comment by mythrilowns** [comment]
@bigshaw3 Hi :) , i also have the 10.11.2 version and i tried to use the app. Sadly all i got was a prohibited sing :( . I fixed the problem by following the simple tutorial but i'm sad because i want the black screen on my MBP!!!

**Comment by bigshaw3** [comment]
Yes I hope they update their amazing app sometime soon. The white boot just doesn't match smoothly with the aluminum MacBook hardware:( And if they did the dead battery symbol screen to the El Capitan dead battery logo that would be a cool plus too :)
