### ISSUE TITLE
Dark boot problem

### ISSUE THREAD

**Issue by codebreede** [w0lfschild/DarkBoot#39]
There is a problem with dark boot when installing it on El Capitan, if you have SIP disabled then you install dark boot, SIP will get bugged and show as enabled and the only way to disable it again is to reinstall os x on top of the old installation.

Early 2011 13" MBP

**Comment by vallovic** [comment]
I can confirm this issue. I had SIP disabled, installed DarkBoot and then my Mac wouldn't boot. Tried some solutions to repair it but: 
- in Single User it crashed right away in the "boot.efi" file.
- in Recovery Mode used the Terminal to navigate to "/System/Library/CoreServices" but file boot_stock.efi" there wasn't even there to try to substitute the "boot.efi". Besides that my Macintosh HD was mounting as read-only and even trying to force it to mount as RW had no success.

Finally, the only solution to fix it was to "Reinstall OSX" through the Recovery Mode.

I think that should be a warning related to this problem in the main page and in the readme.md file.
