### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by oc-tk** [w0lfschild/DarkBoot#4]
Just not working

**Comment by w0lfschild** [comment]
What do you get if you open terminal and type this after running the app?

```
bless --info /
```

**Comment by oc-tk** [comment]
Mac-c82a1454e01d:~ tomaszkaczmarzyk$ bless --info /

finderinfo[0]: 9553844 => Blessed System Folder is /dboot

finderinfo[1]: 9553850 => Blessed System File is /dboot/black_boot.efi

finderinfo[2]:      0 => Open-folder linked list empty

finderinfo[3]:      0 => No alternate OS blessed file/folder

finderinfo[4]:      0 => Unused field unset

finderinfo[5]: 9553844 => OS X blessed folder is /dboot

64-bit VSDB volume id:  0x7C7DAE93574246A5

Mac-c82a1454e01d:~ tomaszkaczmarzyk$ 

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by w0lfschild** [comment]
Have you restarted twice? Are you using another boot loader like refind? Because it definitely looks like it's working.

**Comment by oc-tk** [comment]
just normal bootloader. yes i rebooted twice, method with terminal doesnt work for me too.

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by oc-tk** [comment]
we can teamviewer if you want ofc

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by w0lfschild** [comment]
Okay not at my computer right now though.

**Comment by oc-tk** [comment]
you are from?

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by w0lfschild** [comment]
USA pacific standard time

**Comment by oc-tk** [comment]
Okay im from Poland. When you will have access to your Mac just let me know and then team viewer session

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by w0lfschild** [comment]
I'm on now.

**Comment by oc-tk** [comment]
we can try now but my internet connection will propably suck now. if you want to try just let me know

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by w0lfschild** [comment]
Sure lets try.

**Comment by oc-tk** [comment]
im afraid that my internet want be able to handle teamviewer now (internet provider have some technical issues) so i will be aviable after 15 hours. Just send me a message Can we try after 18 hours?

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by oc-tk** [comment]
Im ready, just let me know if u are too

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by terraboss** [comment]
I can agree with that. I'm using 10.10.2 (14C106a) on MBP Late 2011 15" and it's not working.

**Comment by oc-tk** [comment]
im using mbp late 2011 13” maybe thats why...

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by terraboss** [comment]
Update #1:
The latest command line version as well as BootXChanger aren't working. Hmm...

Update #2:
The very latest Version 10.10.2 (14C109) shows also no effects. :-1: 

---

> MBP:~ me$ bless --info /
> finderinfo[0]: 8181896 => Blessed System Folder is /dboot
> finderinfo[1]: 8181902 => Blessed System File is /dboot/black_boot.efi
> finderinfo[2]:      0 => Open-folder linked list empty
> finderinfo[3]:      0 => No alternate OS blessed file/folder
> finderinfo[4]:      0 => Unused field unset
> finderinfo[5]: 8181896 => OS X blessed folder is /dboot
> 64-bit VSDB volume id:  0x922DD50244CC5103
> MBP:~ me$   ttt=$(bless --info | grep "Blessed System File"); ttt='/'${ttt#*/}; echo "$ttt";
> /dboot/black_boot.efi
> MBP:~ me$

**Comment by terraboss** [comment]
After trying you're command line script another time and reboot my MBP, I've got a blinken folder with question mark on it. I fixed this by setting up my startup drive again via Yosemite recovery USB stick. This sucks. Although the script was telling me he succeeded. Any clue? 

One thing is curious: The length of the replaced IDs. Could this cause this issue?

Thanks in advance! 

> Welcome
> 
> First you will need to enter your password for some sudo commands
> You won't see your password as you type it, just enter it and press return
> 
> Password:
> 
> Unlocking boot.efi
> Backing up boot.efi to /System/Library/CoreServices/efi_backups/boot_100120012120.efi
> 
> Your ID : Mac-94245A3940C91C80
> hex  ID : 0d01002d00000200000100000000000001000000
> 
> Converting boot.efi to hex
> Checking boot.efi hex for your ID
> Your board ID couldn't be found in boot.efi
> Your board ID will now be added
> Downloading working boot.efi
> ######################################################################## 100.0%
> Moving working boot.efi
> Converting new boot.efi to hex
> Finding ID to replace
> 
> Your ID : Mac-00200A0000C01C00
> Old  ID : Not Found
> 
> Your hex ID : 0d01002d00000200000100000000000001000000
> Old  hex ID : 0e0f7020000f700e00
> 
> Replacing ID
> Replacing boot.efi and cleaning up /tmp
> Adjusting permissions and locking boot.efi
> 
> Success!
> Now all you need to do is reboot twice.
> Would you like to reboot now? (y/n):

(note: I replaced some numbers by zero for privacy purpose)

**Comment by w0lfschild** [comment]
@terraboss 

You can clearly see it's not finding an ID.

> Old ID : Not Found

Your ID is normal length. Apple does not use ID's other than 8 char and 16 char.

Also nulling out numbers isn't protecting you from anything rather just making your post less helpful. This isn't sensitive info, it's the type of Board your computer has, posting what model of computer you have is giving away more info.

I would try just manually doing the process.
http://forums.macrumors.com/showthread.php?t=1751446

**Comment by oc-tk** [comment]
so when can we make an teamviever session?

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by w0lfschild** [comment]
Now if you want.

**Comment by oc-tk** [comment]
in next 30 minuts. ok?

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by w0lfschild** [comment]
Sure.

**Comment by oc-tk** [comment]
## 

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by oc-tk** [comment]
blink folder :/ damn i will try to fix it now

**Comment by oc-tk** [comment]
ok fixed, just startup things (cmd + r and startup) still grey (default
color)... whats now?

**Comment by w0lfschild** [comment]
Shoot sorry about that. I really am not sure what the issue is. Must have something to do with your board ID already being in the efi file or something.

**Comment by w0lfschild** [comment]
You could email me a copy of your stock efi file and the output of

```
 var_ID=$(ioreg -p IODeviceTree -r -n / -d 1 | grep board-id);var_ID=${var_ID##*<\"};var_ID=${var_ID%%\">};echo $var_ID 
```

**Comment by terraboss** [comment]
Mac-94245A3940C91C80

Next try:

> Unlocking boot.efi
> Backing up boot.efi to /System/Library/CoreServices/efi_backups/boot_150129144254.efi
> 
> Your ID : Mac-94245A3940C91C80
> hex  ID : 4d61632d39343234354133393430433931433830
> 
> Converting boot.efi to hex
> Checking boot.efi hex for your ID
> Your board ID already exists in boot.efi
> Would you like to REMOVE your ID? (y/n): y
> Your board ID will now be nulled
> Replacing boot.efi and cleaning up /tmp
> Adjusting permissions and locking boot.efi
> 
> Your ID has been removed.
> logout

And relaunching the script after reboot:

> Unlocking boot.efi
> Backing up boot.efi to /System/Library/CoreServices/efi_backups/boot_150129144717.efi
> 
> Your ID : Mac-94245A3940C91C80
> hex  ID : 4d61632d39343234354133393430433931433830
> 
> Converting boot.efi to hex
> Checking boot.efi hex for your ID
> Your board ID couldn't be found in boot.efi
> Your board ID will now be added
> Downloading working boot.efi
> ######################################################################## 100.0%
> Moving working boot.efi
> Converting new boot.efi to hex
> Finding ID to replace
> 
> Your ID : Mac-94245A3940C91C80
> Old  ID : Not Found
> 
> Your hex ID : 4d61632d39343234354133393430433931433830
> Old  hex ID : 4e6f7420466f756e64
> 
> Replacing ID
> Replacing boot.efi and cleaning up /tmp
> Adjusting permissions and locking boot.efi
> 
> Success!
> Now all you need to do is reboot twice.
> Would you like to reboot now? (y/n): 

Nothing happens.
