### ISSUE TITLE
Code Signing issues

### ISSUE THREAD

**Issue by tylamb19** [w0lfschild/DarkBoot#42]
With the released app, Sparkle generates a warning that says to sign the application or updates with a DSA key. A screenshot is attached.
![screen shot 2016-04-19 at 4 03 54 pm](https://cloud.githubusercontent.com/assets/13257508/14654088/fe77a462-0649-11e6-90a0-70d612661a24.png)

**Comment by w0lfschild** [comment]
Yup I think you'll need to manually update the next update. I rushed this one out a bit to avoid more issues of people ending up with non-booting devices.
