### ISSUE TITLE
BootXChanger? I don't get it

### ISSUE THREAD

**Issue by MrRod** [w0lfschild/DarkBoot#43]
Why DarkBoot is now suddenly BootXChanger? It doesn't even give you the option for "dark boot" anymore, what this originally was meant to do.

**Comment by w0lfschild** [comment]
It's using BootXChanger as a base but has the added ability of being able to change the boot cool whereas BootXChanger could only customize the image.

I'll add in buttons to specifically choose the black or gray boot screens but for now you can just pick any color for your boot color. You can still choose a dark boot now by just picking black as the boot color.

Right now it's not totally finished I just have a lot of work and not a lot of time to spend on side projects.

**Comment by MrRod** [comment]
Thanks for the answer. This isn't really working on 10.11.4 at the moment, though. Only the Apple logo can be changed but not the gray color to, say, black (with SIP disabled). Looking forward to a more complete version, which hopefully will swap the Apple logo to white when choosing the dark boot.

**Comment by dabrain13** [comment]
The color change should be working in 10.11.4. make sure the DarkBoot LaunchDaemon was run on boot.

Open terminal and run:

sudo launchctl list | grep "darkboot"

If you don't get any output, try installing again.

**Comment by w0lfschild** [comment]
Yup I based this off of @dabrain13's https://github.com/dabrain13/DarkBoot-NVRAM an confirmed it works on several machines so I'm not sure what the issue is for you @MrRod without more information.

**Comment by w0lfschild** [comment]
New version is out with some improvements and a UI that is more inline with my other applications.
