### ISSUE TITLE
How to disable completely?

### ISSUE THREAD

**Issue by purrydot** [w0lfschild/DarkBoot#44]
I installed Dark boot and now my macbook pro 13" 2015 (not sure if that helps?) reboots with this putrid neon green color, nothing I do changes the color either, and I just want it to go back to being defaut again, what can I do to remove this?

**Comment by w0lfschild** [comment]
Delete `/Library/LaunchDaemons/com.dabrain13.darkboot.plist` and then reboot twice.

**Comment by devilsrider** [comment]
I'm new to Mac, and I'm having the same problem. There isn't any LaunchDaemons folder (there is LaunchAgents), so right now I'm stuck with this green color! Please help!!!

**Comment by w0lfschild** [comment]
Well you can also open Darkboot and choose the default boot color and then apply.

That should accomplish the same thing. You might need to reboot twice to see the changes applied.

**Comment by fjdr** [comment]
In my Mac is not the file after:  /Library/LaunchDaemons/com.dabrain13.darkboot.plist

**Comment by immvic** [comment]
I can't find this file /Library/LaunchDaemons/com.dabrain13.darkboot.plist

**Comment by w0lfschild** [comment]
@Viki-Chi-Macbook 

You might also look for `/Library/LaunchDaemons/com.macenhance.dbcolor.plist`
