### ISSUE TITLE
Crashes on Sierra

### ISSUE THREAD

**Issue by cmdshft** [w0lfschild/DarkBoot#46]
Latest app crashes on sierra. Offers to run in "unstable" manner. Also, no option to just use white apple/loadbar and black background.

**Comment by w0lfschild** [comment]
What version are you using? It runs fine for me.

I'd need to see the crash log.

**Comment by cmdshft** [comment]
Using latest version on Sierra PB6. I've attached the crash log.

[darkboot_crashlog.txt](https://github.com/w0lfschild/DarkBoot/files/428645/darkboot_crashlog.txt)
