### ISSUE TITLE
Stops working after upgrade to macOS Sierra Beta 7

### ISSUE THREAD

**Issue by sidpagariya** [w0lfschild/DarkBoot#47]
After I upgraded to macOS Sierra Dev Beta 7 from the 6th Beta, and after upgrading to the newest version of DarkBoot, The color gets set and everything is fine until I reboot multiple times just to see that the color is applied and there is a BootLogo image in the CoreServices folder but that does not appear when booting up.... I have attached a picture for you guys to see...
Please help!
Thanks,
Sid.

 [](url)
<img width="502" alt="bootlogo" src="https://cloud.githubusercontent.com/assets/10685754/18037649/7d038034-6d57-11e6-8b7f-396d269c0847.png">

**Comment by w0lfschild** [comment]
Try the latest version of the app.

**Comment by sidpagariya** [comment]
Hi! Just a quick question...why don't I see the BootLogo.png appear in the CoreServices Folder? Did you change the path? I mean, I don't see changes regarding the file path though...so I wasn't sure...
Thanks!
Sid.

**Comment by w0lfschild** [comment]
It's now using /Library/Caches/BootLogo.png

Coreservices was in a system folder and protected from modification by system integrity protection.

**Comment by sidpagariya** [comment]
Huh, interesting. the app doesn't set the color but it does set the image. Unfortunately, on boot, the image still does not appear for me (Latest macOS Dev Beta).
😢

**Comment by sidpagariya** [comment]
You change it in the com.apple.....boot.plist file, but the darkbrain plist file is unchanged...
I wasn't sure why that wasn't working...

**Comment by w0lfschild** [comment]
Maybe try saving your image in a different format and or size?

**Comment by sidpagariya** [comment]
Ok! Will give it a try... Could you check on your computer with the above attached image? I will make a smaller image of the same...
Thanks!

**Comment by sidpagariya** [comment]
Hi! It doesn't seem to work still...any suggestions? I can try any other stuff you could suggest and any help would be greatly appreciated!
Thanks so much!
Sid.

**Comment by w0lfschild** [comment]
I'm pretty sure the logo will not show if you have either:
File vault enabled
Automatic login on boot enabled

Don't think there is anything I can do about either of those issues

**Comment by sidpagariya** [comment]
I do have automatic login enabled... Thanks, and I will try again!
