### ISSUE TITLE
Still not working....

### ISSUE THREAD

**Issue by ckjbeos** [w0lfschild/DarkBoot#48]
Hi i have macbook pro 2012 series
i try the app, it prompt me password, i enter it ok, but after reboot the screen still stay the original.
I don't understan why it's not work i have a macmini 2012 at home and on it it work !!!!
don't understand why it's not have effect.
After restart the app the color set stay to gary ;(

have you some test i can made to see wher it's not work ?

Regards,
Cedric

**Comment by w0lfschild** [comment]
Probably some issue with permissions and I'm guessing the app is failing to save the launch plist at `/Library/LaunchDaemons/com.dabrain13.darkboot.plist`

**Comment by ghost** [comment]
I have the same issue on my late 2012 13" MacBook Pro running macOS Sierra 10.12.

I open DarkBoot, change the color to black, click apply, enter my password, and when i reboot the boot screen is the default one.

I've updated to the latest version of DarkBoot (4.0.6) and it made no difference.

Do I need to disable SIP?

**Comment by ckjbeos** [comment]
Hi, @w0lfschild 
I see but not find the file you say /Library/LaunchDaemons/com.dabrain13.darkboot.plist
have you a method to install manually step by step ? to find where that not work.

Rgards,
Cedric

**Comment by w0lfschild** [comment]
http://forums.macrumors.com/threads/guide-black-boot-screen-white-apple-logo-on-unsupported-macs-boot-efi-hack.1751446/page-7#post-22742480

https://github.com/dabrain13/DarkBoot-NVRAM

**Comment by rohmanhm** [comment]
hi @w0lfschild , whether it supports to macOS Sierra?

**Comment by ardacebi** [comment]
@w0lfschild The method you gave me it's a great idea but still having issues about it.

Here is the issue: https://github.com/dabrain13/DarkBoot-NVRAM/issues/1
