### ISSUE TITLE
MacOS Sierra (10.12) seems to change things a bit...

### ISSUE THREAD

**Issue by SemoTech** [w0lfschild/DarkBoot#49]
Running MacOS Sierra 10.12 (16A323) on MacPro5,1 with DarkBoot Version 4.0.6 (106)

Can DarkBoot be configured to allow one to select the "Current Boot Image" for Sierra, in order to have the same effect as placing a custom "com.apple.desktop.admin.png" image in /Library/Caches did in El Capitan?  I want to keep my Boot image different than my desktop background image....

It seems you can drag an image (tried both PNG and JPG formats) to the DarkBoot app and place on top of the default apple logo, but it will still not appear at boot/login time...

See screenshot here:  http://www.screencast.com/t/BgkeXbKH

**Comment by SemoTech** [comment]
Hi w0lfschild, any luck with this?

**Comment by w0lfschild** [comment]
The boot image option is something instead of the apple logo when booting, not your login screen image.

**Comment by SemoTech** [comment]
Thanks w0lfschild.  Figured it out.  Turns out to get the custom Login Screen in Sierra you need:

1) Custom image called "com.apple.desktop.admin.png" placed in [Macintosh HD/Library/Caches] NOT ~/Library/Caches
2) Image needs to be 8Bit RGB PNG in Layer 0, and not background layer! (click the layer in photoshop) 
![screen shot 2016-10-12 at 09 11 12](https://cloud.githubusercontent.com/assets/1452100/20608263/36d22156-b24e-11e6-998e-c3b90f4d3f71.png)

Keep up the great work!

**Comment by w0lfschild** [comment]
👍

**Comment by w0lfschild** [comment]
New version can automate this (not the making it a .png part). Also locks the file so it doesn't get replaced if you change your desktop wallpaper.

**Comment by SemoTech** [comment]
Hi w0lfschild, tried the new DarkBoot version and **it works**, thank you, with one caveat:  It changes the login screen at fresh boot-up, but if the machine goes to sleep the login screen for the current user reverts to the blurry sierra default.  MacOS is 10.12.1, is there a fix?  Thanks in advance!!

**Comment by w0lfschild** [comment]
Yeah I've noticed that as well but I have no idea where it's pulling that image from or if it's like software generated on the fly. If I figure out how to change it, I'll add that functionality to Dark Boot.

**Comment by w0lfschild** [comment]
The latest version can edit the login screen now as well as made a fix for the lock screen so it should work with pretty much any image you throw it's way.

Login screen can even use a gif 👍
