### ISSUE TITLE
Not working (10.10.2 (14C109))

### ISSUE THREAD

**Issue by xtreme1690** [w0lfschild/DarkBoot#5]
Stupidly updated without remembering that it may break the DarkBoot...
Even with latest version, still nothing. Rebooted 3 times just incase.
Thought this would be helpful too:

MacBook:Desktop Billy$ bless --info /
finderinfo[0]: 4073843 => Blessed System Folder is /dboot
finderinfo[1]: 4073849 => Blessed System File is /dboot/black_boot.efi
finderinfo[2]:      0 => Open-folder linked list empty
finderinfo[3]:      0 => No alternate OS blessed file/folder
finderinfo[4]:      0 => Unused field unset
finderinfo[5]: 4073843 => OS X blessed folder is /dboot
64-bit VSDB volume id:  0xA9D6A557F144C855

Any suggestions?

**Comment by w0lfschild** [comment]
I dunno really. You could delete the /dboot folder and re-run the application.

**Comment by oc-tk** [comment]
so this is your advice?

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by xtreme1690** [comment]
I tried removing the /dboot stuff and running the .command version and my entire installation died on its ass. Had to restore a 10.10.1 backup... Will try this again at some other time.

**Comment by xtreme1690** [comment]
Update: Found the issue (With the script version anyway) It seems to corrupt the boot.efi, made it a locked 20kb file, once i trashed it and used the boot.efi inside the dboot application bundle? System booted without incident... Now to get the dark boot back somehow...hmmm

**Comment by oc-tk** [comment]
so replace boot.efi with one from dboot folder? and what next?

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by xtreme1690** [comment]
Thats only if you have the symptom i did, which was that the entire install becomes unbootable. Not sure why now but using the old .command version corrupts the boot.efi at /system/library/coreservices and makes it a useless 20kb file.

**Comment by oc-tk** [comment]
after old command it want boot so now it will reboot properly?

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by xtreme1690** [comment]
Ah, i see why the old .command version is broken. Inside the script is a link to download a working boot.efi right from this site but the link is dead (probably due to their being a newer version (the dboot application) and so thats why the useless 20kb file is there, its a dummy file. So, advice to all, DO NOT use the old .command version as IT WILL DESTROY your install. Im trying to see if i can get dboot to work now, not sure why it doesnt...

**Comment by w0lfschild** [comment]
The dboot application should be working fine on the current release of OSX.

**Comment by xtreme1690** [comment]
Well im not sure why it isnt for me :P

**Comment by oc-tk** [comment]
so just now copy boot.efi from dboot and then run app?

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by xtreme1690** [comment]
I may have solved this, it needs testing by another party who cant get it working on either 10.10.1 or 10.10.2. DO THE FOLLOWING: Run the dark boot application and set it for BLACK, now goto the root of your hard disk where there is now a dboot folder (So /dboot) , see the 2 new files? open a new finder window and navigate to /System/Library/CoreServices , BACKUP the boot.efi in there already and then delete it (This is safe!) , go back to the dboot finder window, right click the black boot.efi file and select COPY, return to the /CoreServices finder window, right click in the white space where the old boot.efi was and select PASTE. Authorize the file copy and then reboot twice, that is what i did and its working perfectly...for now.

**Comment by xtreme1690** [comment]
Oh, also! Once you've copied the black boot.efi file RENAME IT to boot.efi, THEN reboot twice... THIS IS CRUCIAL or your system wont boot!

**Comment by xtreme1690** [comment]
Final update, for now: Just confirmed for myself that this works on 10.10.1 and 10.10.2, essentially i think im doing what the program should, but for some reason it doesnt work for me so heres a more organised step by step list:

1.) Download Dark Boot application, run it and select Black, enter your password and wait for the application to self terminate. (I did not set it to check at each boot either)

2.) Open 2 finder windows, in one of them navigate to /dboot and in the other navigate to /System/Library/CoreServices

3.) Goto the /dboot finder window, right click the black_boot.efi file and select Copy.

4.) Goto the CoreServices finder window, make a backup of the boot.efi file in here and then erase the one in the CoreServices folder. (Sidenote: If you have a locked boot.efi file that is 20kb or so then dont bother backing it up and just use the delete command in terminal. (Sudo rm /System/Library/CoreServices/boot.efi), you will be asked to override the files locked permissions, type Y and press enter, the file will be erased. Not sure why but sometimes the program seems to hiccup and messes this file up...for me anyway!)

5.) In the space where the old boot.efi was, right click and select Paste. You will be asked for your password, type it to allow the file copy. Inside the CoreServices folder will now be a black_boot.efi file, rename this so its just boot.efi , again you will need your password for this so enter it and the file will be renamed.

6.) Reboot twice!

This worked absolutely perfect for me, im not sure why but i suspect that (for me anyway) after the program is done patching the .efi files in the /dboot folder for my system, something gets messed up with the boot.efi in the CoreServices folder. Im certain its software related somehow as the issue can be replicated each and every time. Im just not sure which side of software, this application or the OS. Probably the OS since w0lfschild confirms it working elsewhere (As seen above in his reply :) )

Many thanks to w0lfschild though for the hard work and effort put into this so we can have these little quirks with our systems :D I think the black boot screen looks cooler anyway :P

**Comment by w0lfschild** [comment]
Hmm it must be something related to bless. I'm just not sure what or why it doesn't seem to work for everyone.

I'm updating the command line version to fix the broken link and I'm also updating the app with some minor changes atm.

**Comment by oc-tk** [comment]
In next few hours I will let you know if this method works or not. I will let you know asap. Now make white/black boot screen for idevice :D

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by terraboss** [comment]
Yeah baby, solved. BIG Thanks to you guys !!!

**Comment by jcr-** [comment]
I followed xtreme1690's method and replaced my locked boot.efi file with the renamed black_boot.efi file from the dboot folder. Two boots later, blackness. Prior to that the boot remained grey despite selecting Black in the Darkboot 1.2 / 2.2 app.

17-inch MacBook Pro mid 2010 OS 10.10.2

bless --info / indicated that dboot/black_boot.efi was correctly blessed. Not sure what is going on here, unless somehow the coreservices boot.efi just gets priority over the blessed efi.

I also had a flashing ? folder issue, as I had tried the command-line version first. Obviously that is not related.

**Comment by w0lfschild** [comment]
Interesting.

I think I'll add a check-box to use the old method to the app.

**Comment by xtreme1690** [comment]
Glad to see i've helped some people! [_Does a little victory dance_] Keep up the good work w0lfschild :D

**Comment by oc-tk** [comment]
yep its working :D

Z poważaniem

Tomasz Kaczmarzyk

www.itsilesia.com

**Comment by w0lfschild** [comment]
Okay I've made the app use something quite similar to the original method I'm guessing it should work for everyone now.

**Comment by xtreme1690** [comment]
Awesome!

Just to add, a symptom really more than anything but just letting you know! If you boot your Mac from a external drive that does Not have the black boot screen set in the boot.efi and then boot from the internal drive later, after 2 reboots (or 1 cold start) you will get the grey boot screen. Simply reboot your Mac and the black one will return :)
