### ISSUE TITLE
Doesnt work on my macbook pro

### ISSUE THREAD

**Issue by jensefrens** [w0lfschild/DarkBoot#51]
MacBook Pro (13-inch, Early 2011)
MacOS 10.12.1 (16B2555)

**Comment by w0lfschild** [comment]
Try the latest version?

I'm also not sure if this works with FileVault enabled.

**Comment by jensefrens** [comment]
i use the latest version and file vault is not enabled

**Comment by w0lfschild** [comment]
Which part isn't working? What's the result of running these commands in terminal?

```
ls -l /Library/LaunchDaemons/com.dabrain13.darkboot.plist
more /Library/LaunchDaemons/com.dabrain13.darkboot.plist
```
