### ISSUE TITLE
Doesn't work in macOS Sierra 10.12.1

### ISSUE THREAD

**Issue by RickyVercetti** [w0lfschild/DarkBoot#55]
In iMac 27" Late 2009. Thanks!

**Comment by w0lfschild** [comment]
What part isn't working?

If it's the boot color option what do you get as a result from these two terminal commands?

```
ls -l /Library/LaunchDaemons/com.dabrain13.darkboot.plist
more /Library/LaunchDaemons/com.dabrain13.darkboot.plist
```

**Comment by Jahjahshaka** [comment]
It might help:

Corys-MBP:~ CJ$ ls -l /Library/LaunchDaemons/com.dabrain13.darkboot.plist
-rw-r--r--@ 1 CJ  wheel  483 Dec  1 18:50 /Library/LaunchDaemons/com.dabrain13.darkboot.plist
Corys-MBP:~ CJ$ more /Library/LaunchDaemons/com.dabrain13.darkboot.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Label</key>
        <string>com.dabrain13.darkboot</string>
        <key>ProgramArguments</key>
        <array>
                <string>/usr/sbin/nvram</string>
                <string>4d1ede05-38c7-4a6a-9cc6-4bcca8b38c14:DefaultBackgroundColor=%19%01%30</string>
        </array>
        <key>KeepAlive</key>
        <false/>
        <key>RunAtLoad</key>
        <true/>
</dict>
</plist>

**Comment by BaReinhard** [comment]
This is using the latest sierra, on Mac Book Pro Late 2011
```
> 
> Bretts-MacBook-Pro-2:~ Brett$ ls -l /Library/LaunchDaemons/com.dabrain13.darkboot.plist
> -rw-r--r--  1 root  admin  482 Dec 10 22:04 /Library/LaunchDaemons/com.dabrain13.darkboot.plist
> Bretts-MacBook-Pro-2:~ Brett$ 
> Bretts-MacBook-Pro-2:~ Brett$ more /Library/LaunchDaemons/com.dabrain13.darkboot.plist
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
>         <key>KeepAlive</key>
>         <false/>
>         <key>Label</key>
>         <string>com.dabrain13.darkboot</string>
>         <key>ProgramArguments</key>
>         <array>
>                 <string>/usr/sbin/nvram</string>
>                 <string>4d1ede05-38c7-4a6a-9cc6-4bcca8b38c14:DefaultBackgroundColor=%00%00%00</string>
>         </array>
>         <key>RunAtLoad</key>
>         <true/>
> </dict>
> </plist>


For me, the boot logo doesn't work, but the boot color works and so does the login png.
>  This is using the latest sierra, on Mac Book Pro Late 2011
> 
> Bretts-MacBook-Pro-2:~ Brett$ ls -l /Library/LaunchDaemons/com.dabrain13.darkboot.plist
> -rw-r--r--  1 root  admin  482 Dec 10 22:04 /Library/LaunchDaemons/com.dabrain13.darkboot.plist
> Bretts-MacBook-Pro-2:~ Brett$ 
> Bretts-MacBook-Pro-2:~ Brett$ more /Library/LaunchDaemons/com.dabrain13.darkboot.plist
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
>         <key>KeepAlive</key>
>         <false/>
>         <key>Label</key>
>         <string>com.dabrain13.darkboot</string>
>         <key>ProgramArguments</key>
>         <array>
>                 <string>/usr/sbin/nvram</string>
>                 <string>4d1ede05-38c7-4a6a-9cc6-4bcca8b38c14:DefaultBackgroundColor=%00%00%00</string>
>         </array>
>         <key>RunAtLoad</key>
>         <true/>
> </dict>
> </plist>


For me, the boot logo doesn't work, but the boot color works and so does the login png.
```

**Comment by w0lfschild** [comment]
@bar1792 

I'm pretty sure the boot logo will not show if you have either:
File vault enabled
Automatic login on boot enabled

Don't think there is anything I can do about either of those issues

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92

**Comment by TheFirstFarmerBob** [comment]
10.12.6. Upon startup all kinds of Virus protection goes off in regard to PUA. I trust that's what you use to make the changes to the system. Upon fixing that, opening get stuck in: "Verifying "Dark Boot.app. The progress bar starts and will not move past 2/3's.

![screen shot 2018-12-05 at 7 00 51 pm](https://user-images.githubusercontent.com/42600524/49556238-200e0880-f8c0-11e8-9c3b-16f4f0d6debc.png)

![screen shot 2018-12-05 at 6 44 02 pm](https://user-images.githubusercontent.com/42600524/49556245-2a300700-f8c0-11e8-8b4e-3c14522e6f28.png)

![screen shot 2018-12-05 at 6 44 12 pm](https://user-images.githubusercontent.com/42600524/49556250-2c926100-f8c0-11e8-8f8c-18d2d6785830.png)
