### ISSUE TITLE
Changed background color but can't change logo

### ISSUE THREAD

**Issue by ardacebi** [w0lfschild/DarkBoot#57]
Hi,

I changed the background color by changing the .plist file manually on my MacBook Pro Mid 2012 but I can't change the boot logo. How can I do that? The application doesn't work.

**Comment by Jahjahshaka** [comment]
[com.apple.Boot.plist.zip](https://github.com/w0lfschild/DarkBoot/files/629354/com.apple.Boot.plist.zip)
put this file in Library/Preferences/SystemConfiguration, replace the old one (keep it somewhere in case). the BootLogo image should be stored in Library/Caches. If not, create one in png (84/103 pixels) and call it BootLogo.png

**Comment by ardacebi** [comment]
Thanks. I'll try that and let you know what happened.

**Comment by w0lfschild** [comment]
I'm pretty sure the logo will not show if you have either:
File vault enabled
Automatic login on boot enabled

Don't think there is anything I can do about either of those issues

**Comment by Darkomen78** [comment]
Hi, there's a little problem on 10.12.3, /Library/Preferences/SystemConfiguration/com.apple.Boot.plist is a "rootless-SIP" file.

**Comment by w0lfschild** [comment]
@Darkomen78 can't really work around that (aside from the obvious disable SIP to edit file).

RIP custom boot logos.

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92
