### ISSUE TITLE
Can't change back the blur login image.

### ISSUE THREAD

**Issue by nhvk** [w0lfschild/DarkBoot#58]
I have a problem that I can't make the wallpaper photo appear blur on login screen like normal, even I have clicked the default button and restarted the Mac. Are there anyway to solve this problem? By the way, my Mac is on 10.11.6 El Capitan, the Bootlogo changing is also not working. Thank you for the app, keep it up!

**Comment by w0lfschild** [comment]
Okay yeah I see why this is happening. I'll fix it soon but just open ```/Library/Caches/com.apple.desktop.admin.png``` and unlock the file then delete it and I'm pretty sure OS X should regenerate a new picture for you or you can force it to update by choosing a new wallpaper.

**Comment by nhvk** [comment]
Okay. I've done it. Thank you! I'm waiting till the Bootlogo changer works also :)
