### ISSUE TITLE
partial working

### ISSUE THREAD

**Issue by appletechgeek** [w0lfschild/DarkBoot#59]
tried it but the first half of the loading progress the apple logo is normal but when the os is almost booted the apple logo and background change to dark  mode
when booting into recovery mode the dark mode is always
if wanted i can make a youtube video

**Comment by yongjiajun** [comment]
I have my SIP disabled, reapplied the dark boot settings again and everything works fine now.

**Comment by appletechgeek** [comment]
It works for me now  afther alot of reboots strange is when i remove my hard drive my boot is stilll dark what magic is this?

Sent from my iPhone

On 14 Dec 2016, at 05:27, Jia Jun Yong <notifications@github.com<mailto:notifications@github.com>> wrote:


I have my SIP disabled, reapplied the dark boot settings again and everything works fine now.

-

**Comment by w0lfschild** [comment]
@appletechgeek it saves to nvram which is not on your hard drive.

https://support.apple.com/en-us/HT204063
