### ISSUE TITLE
Can't seem to go back to normal

### ISSUE THREAD

**Issue by mykamel** [w0lfschild/DarkBoot#60]
I tried using this on my clean install of Sierra. It seems to work, but shows a bunch of distortion at login. I didn't; think the distortion was worth the dark boot screen. Now I can't seem to get it to go back to normal.

I have tried zapping the p-ram. It goes to a white color, font a little blurry, then a colored distortion after typing password, in the upper half of the screen.

Is there a file I can replace or something to put it back to stock?

I have tried replacing boot.efi from the installer app, but no change.

**Comment by w0lfschild** [comment]
`/Library/LaunchDaemons/com.dabrain13.darkboot.plist`

**Comment by ghost** [comment]
Hi,

I want to go back to normal but failed. I deleted file at "/Library/LaunchDaemons/com.dabrain13.darkboot.plist".

Any suggestion?

**Comment by mykamel** [comment]
I did Wolfgang's solution, and it worked for me... I think you might need to reboot twice?

**Comment by w0lfschild** [comment]
Yes you have to reboot twice.

**Comment by ghost** [comment]
Thank u all. I have solved this problem.

Best Regards,
Leonard
