### ISSUE TITLE
Boot colour

### ISSUE THREAD

**Issue by metriics** [w0lfschild/DarkBoot#61]
Boot colour changes to previously saved settings after new settings are applied. I can check this by selecting new settings, applying them and quitting the app. After reopening the app, the old selection is still there as if it is reverted or wasn't saved at all. SIP is disabled, I have cDock installed with no modifications. 

edit: Heres a link to a video of the issue. https://youtu.be/bdHcLZ6MsCM

**Comment by w0lfschild** [comment]
Should be fixed in 6.0.2
