### ISSUE TITLE
Custom Boot Logo not working

### ISSUE THREAD

**Issue by jingan0904** [w0lfschild/DarkBoot#64]
In my previous issue you directed me to Issue #57, does that mean i cannot have a custom Boot Logo for my MacBook Pro (Early 2015)?

**Comment by w0lfschild** [comment]
If System Integrity Protection is on and you're running the latest version of Sierra then that is correct. You could disable SIP and give it a shot and it should work then. Still no guaranties though.

**Comment by jingan0904** [comment]
So I must switch on **system integrity protection**?
Because currently I have my **system integrity protection** off.

**Comment by w0lfschild** [comment]
No, I'm sorry I'm not sure exactly what the issue you're having is.

You might try manually editing your boot image.

https://beak90.wordpress.com/2010/08/11/how-to-change-the-mac-boot-logo-without-3rd-party-software-by-hand/

**Comment by jingan0904** [comment]
Umm....... I tried manually editing my boot image, it still does not work. I thank you for the time to fix this error on your application. Keep up the good work!😆

**Comment by jingan0904** [comment]
So is this fixable?

**Comment by brianfos** [comment]
What file formats are allowed for the boot image? Will TIFF work? PNG? Others? Are there size requirements or limitations? I correctly see a TIFF file showing in Dark Boot, but it does not show up when I reboot.

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92
