### ISSUE TITLE
DarkBoot MacBook Pro 2015 Mac OS Sierra 10.12.5 Beta

### ISSUE THREAD

**Issue by Ipeleng** [w0lfschild/DarkBoot#66]
Currently Darkboot is not working on my MacBook Pro. I even have SIP disabled

**Comment by ITJesse** [comment]
Confirmed not work properly on MacBook Pro (15-inch, 2016)
OS: 10.12.5 Beta (16F54b)

`Boot Color` has been changed but the `Boot Image` take no effect.

**Comment by w0lfschild** [comment]
@ITJesse 

It has to do with the file `/Library/Preferences/SystemConfiguration/com.apple.Boot.plist` being protected by System Integrity Protection recently.

It means that SIP has to be off in order to edit the logo.

**Comment by Ipeleng** [comment]
I have disable System integrity Protection. Im just wondering is there why i could manually enter the icon file into the boot.plist?

**Comment by Ipeleng** [comment]
Any updates?

**Comment by ITJesse** [comment]
I have turned SIP off and the FileVault is on.

**Comment by Ipeleng** [comment]
@ITJesse did the logo change work for you?

**Comment by ITJesse** [comment]
No it didn't.

**Comment by Ipeleng** [comment]
@ITJesse Ahhh you dont know how bad i want this mod to work lol. I saw a post on reddit and now i need it

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92
