### ISSUE TITLE
Not working in Sierra

### ISSUE THREAD

**Issue by replyvishwajeet** [w0lfschild/DarkBoot#67]
Not able to change Logo in Sierra.

**Comment by w0lfschild** [comment]
It has to do with the file `/Library/Preferences/SystemConfiguration/com.apple.Boot.plist` being protected by System Integrity Protection recently.

It means that SIP has to be off in order to edit the logo.

**Comment by jingan0904** [comment]
Same thing but my SIP is off already. Also using Sierra

**Comment by Ipeleng** [comment]
@TechnoTew @w0lfschild yeah ive tried using it with SIP off still not able to change boot logo

**Comment by ghost** [comment]
Yeah, is there any way of fixing that? Or will you be making a version that can do that. Thx :)

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92
