### ISSUE TITLE
Not working (macOS Sierra)

### ISSUE THREAD

**Issue by Piipperi** [w0lfschild/DarkBoot#69]
I would like to have gray boot screen for my MacBook Air, but it is not working.
MacBook Air 13" (2015)
macOS Sierra 10.12.6

**Comment by ghost** [comment]
its possible the devolper hasnt said this..or needs,,,but maybe on new mac you need to http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/....

mine worked fine on both air like yours but only changing colour was posssible.the image didnt arrive it glitched between there and not there..ciao

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92
