### ISSUE TITLE
Still errors out

### ISSUE THREAD

**Issue by Evermore707** [w0lfschild/DarkBoot#7]
"The following line is neither a comment, nor does it contain a valid command:

default" 

on 10.10.2

**Comment by w0lfschild** [comment]
Is that from the app or the script?

**Comment by nicola-gigante** [comment]
I get the same error message. The error is from the GUI.

**Comment by Evermore707** [comment]
From GUI/ 2012 MBP, 10.10.2

**Comment by ckjbeos** [comment]
same issue 10.10.2
macbook Air 2012

**Comment by yangm97** [comment]
same issue 10.10.2
macbook pro early 2011

**Comment by w0lfschild** [comment]
Should be fixed now.
