### ISSUE TITLE
How to completely Remove DarkBoot?

### ISSUE THREAD

**Issue by ghost** [w0lfschild/DarkBoot#70]
I installed, but my Mac was unresponsive when pressing home button and it takes couple tries to get it to turn on.

How can I remove darkboot completely and go back to default? 

I'm running 10.12.5 on mbp mid 2012.

**Comment by w0lfschild** [comment]
Delete `/Library/LaunchDaemons/com.dabrain13.darkboot.plist` and then reboot twice.
