### ISSUE TITLE
Works, for a while.

### ISSUE THREAD

**Issue by kaos-kult** [w0lfschild/DarkBoot#71]
This tool successfully changes my boot image, and background colour, until the progress bar gets to about 25%, at which point it fades to the default white on black Apple icon on my MacbookPro13,1

**Comment by kaos-kult** [comment]
Just noticed your reply to a similar issue, I'll certainly update if you ever find a fix 😀

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/62
