### ISSUE TITLE
Can't return to defaults

### ISSUE THREAD

**Issue by Kyledude252** [w0lfschild/DarkBoot#72]
I changed my background colour to blue, but now it's stuck as blue. When I select default colour in Dark Boot, apply changes, then restart the app, it's still on blue. No matter what options I choose, it never actually saves. I just was the regular black background with a white apple logo. I don't want this blue background with a blue/greyish apple logo how do I fully reset this.

**Comment by w0lfschild** [comment]
Delete `/Library/LaunchDaemons/com.dabrain13.darkboot.plist` and then reboot twice.

**Comment by w0lfschild** [comment]
Should be fixed in 6.0.2
