### ISSUE TITLE
Can't restore to default settings

### ISSUE THREAD

**Issue by bycabraljr** [w0lfschild/DarkBoot#73]
My MacBook is an mid 2010 A1342 model. The app turned my boot logo to black as expected. But now I want to restore to it's default settings. At first, the logo shows as grey but at the middle of loading bar, it became black again

**Comment by w0lfschild** [comment]
Delete `/Library/LaunchDaemons/com.dabrain13.darkboot.plist` and then reboot twice.

**Comment by w0lfschild** [comment]
Hopefully this should be fixed with 6.0.1

**Comment by fjdr** [comment]
Cant find that plist
