### ISSUE TITLE
Does it work on MacOS Sierra?

### ISSUE THREAD

**Issue by ghost** [w0lfschild/DarkBoot#76]
I tried it on MacOS sierra and it does not work!! Please tell me there is a way to fix this... if so. You gave a nerd bragging rights at school :D B-)

**Comment by w0lfschild** [comment]
What exactly isn't working for you?

This app still works 100% it just has a lot of caveats that I, with my limited knowledge, don't have any workarounds for. 

1. Custom boot color > works*
2. Custom boot logo > works**
3. Custom login image > works***

\* Requires 2x reboot to see changes and custom colors other than black or gray only last part way though boot. https://github.com/w0lfschild/DarkBoot/issues/60#issuecomment-296744553

\** Requires System Integrity Protection to be disabled on macOS 10.12.3 and above to make changes and requires an image with the right format and dimensions. https://github.com/w0lfschild/DarkBoot/issues/57#issuecomment-279348638

\*** Only shows on fresh login, not wake from sleep. https://github.com/w0lfschild/DarkBoot/issues/49#issuecomment-263069852

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92
