### ISSUE TITLE
It does not work on Mac OS Sierra

### ISSUE THREAD

**Issue by ghost** [w0lfschild/DarkBoot#77]
I have this on my Early 2011 11.6" Macbook Air and it does not work... I disabled the SIP (System Integrity Protection) and it does not work, (I of course switched it back on). Can you see if you can make a version that is available for MacOS Sierra?

P.S. - I am not sure if I have already submitted an issue, if so. That one was not accurate and descriptive. Thank you for understanding.

Have a nice day. :)

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92
