### ISSUE TITLE
Does not run on MacBook5,1 (Late 2008)

### ISSUE THREAD

**Issue by terraboss** [w0lfschild/DarkBoot#8]
![screen shot 2015-03-07 at 22 43 28](https://cloud.githubusercontent.com/assets/69455/6543437/62127e96-c51b-11e4-8bd8-37b0fa2e4020.png)

Any idea? 

This is a Yosemite clean install (v. 10.10.2)

**Comment by derekstavis** [comment]
I'm getting exactly the same error here. MacBook Pro 15" Early 2011, OS X 10.10.2 (14C1510) here.

**Comment by kndol** [comment]
I met this error after updating 10.10.3 beta 5 (14D113c) which I've never seen before.

**Comment by w0lfschild** [comment]
Yeah I'm honestly not sure what specifically is causing this but hopefully it will magically fix itself in the next version :smile:

**Comment by phjils** [comment]
Same same here. iMac 12,1 10.10.2

**Comment by phjils** [comment]
I think the line
curl -# -L -o /tmp/boot.efi https://raw.githubusercontent.com/w0lfschild/DarkBoot/master/resource/boot.efi
is possibly to blame if you're trying to run this through a proxy that doesn't support curl.
EDIT/UPDATE: Works perfectly if you can get a direct connection / export your proxy to curl via shell.
Looking good!

**Comment by w0lfschild** [comment]
Interesting. Thanks for the info.

**Comment by nicola-gigante** [comment]
Still the same problem here. What's the problem?

**Comment by phjils** [comment]
For the meantime I'd suggest using the darkboot.command, it seems to be more reliabale. However, the EFI was overwritten when I updated to the public version of 10.10.3, and I cannot use this tool any more. Every time I run the .command and reboot, I'm taken to the recovery partition. Reboot again, grey screen. I have not managed to return to darkboot, which is a shame...

**Comment by hiu1234** [comment]
just simply remove the line "|| echo -n "default""
i uploaded the modified file unzip it and it should work fine 
![dark boot](https://cloud.githubusercontent.com/assets/8568390/7443608/af5f9eca-f18c-11e4-824c-a0501e0dad65.png)

**Comment by kndol** [comment]
@hiu1234 Good! It works well on 10.10.4 beta. Thank you!

**Comment by phjils** [comment]
@hiu1234 That's odd, becuase I cannot find any reference to that. Are you modifying the app or the .command?

**Comment by hiu1234** [comment]
i have modify the script file in the Dark Boot.app/Contents/Resources folder

**Comment by w0lfschild** [comment]
Should be fixed in version 3.
Sorry this took so long, pretty busy atm.
