### ISSUE TITLE
release 5.2.0 Not Savings Images

### ISSUE THREAD

**Issue by theBadAciDdj** [w0lfschild/DarkBoot#83]
Release 5.2.0 is not saving any images to the boot screen.

I have restarted both the app and the mac several times, with no success. The Login screen did change, which is nice.

Macbook Pro 2015
1.6Ghz, i5 
OS High Sierra 10.13.1

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92
