### ISSUE TITLE
Does not work on 10.13.1!

### ISSUE THREAD

**Issue by dzaro-dev** [w0lfschild/DarkBoot#85]
Dear Wolfshild, 

I found your app very convenient, however, it does not work on 10.13.1 !

Using fseventer, I was tracking the file changes that your program makes and noticed that it changes files on the Preboot partition, however, I was also able to see that these files were overwritten by some other process and then the partition was unmounted. 

Could you please try to fix this issue?

Look forward to hearing from you!

**Comment by w0lfschild** [comment]
Interesting. What file was overwritten? I'm not really sure what the pre-boot partition is but I think it has something to do with APFS.

https://github.com/w0lfschild/DarkBoot/issues/92
