### ISSUE TITLE
DarkBoot not working

### ISSUE THREAD

**Issue by padams24** [w0lfschild/DarkBoot#87]
I tried to use DarkBoot to change my boot logo and colour, but although I applied changes and typed the admin password, when I boot it still shows the apple logo. My settings are saved in the app, but do not affect the boot logo. I am running High Sierra (10.13.3) on a 15" MacBook Pro (early 2015). Please can you help?

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92
