### ISSUE TITLE
Cannot reverse to boot image & color on OS X 10.9

### ISSUE THREAD

**Issue by My2ndAngelic** [w0lfschild/DarkBoot#88]
As title, when I replaced with the new boot image & color, I clicked default and the program reported that it was changed. However, the screen boot up was green and no apple no logo. It cannot reverse the change back.

Version: 5.2.0

**Comment by dastefster** [comment]
@My2ndAngelic I had the same exact issue after trying to restore the default settings. However, **I was able to correct it** by deleting by deleting _Dark Boot's_ plist file from the LaunchDaemons folder.

**path**: `/Library/LaunchDaemons/com.dabrain13.darkboot.plist`

after you've trashed the plist, restart your Mac and everything should be back to normal!

**Comment by My2ndAngelic** [comment]
Confirmed, also you can restore the default boot logo in `/System/Library/Core Services/`
Thanks
