### ISSUE TITLE
Not compatible hardware advice/exclusion

### ISSUE THREAD

**Issue by aonez** [w0lfschild/DarkBoot#9]
Just tested with an old 2009 iMac (iMac9,1). The script made its work (the app just returned the error, same as #7 #8), but rebooted in rescue mode. Fixed it via terminal, thanks to the EFI backup.

Just asking for an exclusion list of known incompatible hardware, as mine, so the command/app will just tell the user: don't do it, won't work :+1:

To get the Mac model, you could use:

```
sysctl hw.model | cut -c 11-
```

If you like the idea, I can make some code too, if no need so.

**Comment by w0lfschild** [comment]
Try version 3, this should work with any machine.
