### ISSUE TITLE
high sierra compatibility

### ISSUE THREAD

**Issue by GraalPK** [w0lfschild/DarkBoot#90]
please add high sierra compatibility

**Comment by GraalPK** [comment]
please respond

**Comment by GraalPK** [comment]
STOP SELF ASSIGNING THINGS LAZY BUTT AND ACTUALLY FIND A WAY TO FIX THIS! IT KEEPS UNMOUNTING AND I FOUND OUT THAT THE LATEST VERSION HAS TOO MUCH BUGS YOU NEED TO TELL ME HOW TO FIX THIS AND IF YOU DO NOT FIX THIS I WILL NEVER TRUST YOU AGAIN I'M SERIOUS! THIS KEEPS UNMOUNTS AND IT DOES OPEN WITH HIGH SIERRA, BUT IT UNMOUNTS EVERY TIME I WANT TO DO IT! THIS CANNOT JUST BE SELF-ASSIGNED YOU IDIOT AND I DON'T CARE IF YOU CALL ME SALTY BECAUSE I FEEL SO ANGERY THAT I LITERALLY NEED TO BE SALTY!
anyways, what i'm trying to note is that you need to let me know if you have a fix to this and i cannot accept no response. literally just please find a fix for once

**Comment by w0lfschild** [comment]
I don't know if I can even fix the issue with the boot image not working. The old method doesn't seem to be working and I have no idea what's changed. There's very little documentation of the boot configuration in general.

I assign issues simply as an indicator that I have read the issue.

🤷‍♂️

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/92
