### ISSUE TITLE
Confusing how to download the latest release.  Many users download 2 year old version.

### ISSUE THREAD

**Issue by varenc** [w0lfschild/DarkBoot#93]
The last release [here](https://github.com/w0lfschild/DarkBoot/releases) is 4.0.5 from 2016.  The [Dark Boot website](https://w0lfschild.github.io/app_dBoot.html) says to download the latest release on the release page which is this out of date version.

But from the readme reveals [this](https://github.com/w0lfschild/app_updates/raw/master/DarkBoot/DarkBoot_master.zip) is the actual latest release to download!

I think some of the issues reported might be from users downloading the older versions and missing out on the recent features.  I'd suggest updating the release!

**Comment by w0lfschild** [comment]
Thanks for pointing that out. I didn't even realize the website was linking to the releases page and not a direct download of the latest version.

**Comment by w0lfschild** [comment]
Fixed 👍

**Comment by melvyn2** [comment]
The downloads link to a closed repo. And when I try to compile this, I get a "module 'CoreImage' not found".
