### ISSUE TITLE
Mac OS Mojave  

### ISSUE THREAD

**Issue by CuauReyes** [w0lfschild/DarkBoot#94]
Hey! i saw that you fixed  some issues, but, now in Mac OS Mojave i found a new issue.
When the OS is starting, and you try to select your user account, the background turns a black color.
i don't know probably could be 'cause i'm in a beta?

**Comment by thang-nm** [comment]
I saw black background too. But i have not use DarkBoot yet. It is Mojave bug.
Did DarkBoot work on Mojave?
