### ISSUE TITLE
Possible bug: login screen after wake-from-sleep doesn't appear

### ISSUE THREAD

**Issue by JayBrown** [w0lfschild/DarkBoot#96]
When I open the lid (MacBook Pro, mid-2010, macOS 10.13.5), the login screen doesn't load. Everything is black, but I see the spinning beach ball, I hear sounds from the system, like "new email received", background scripts are working fine, like the one called by Objective-See's DoNotDisturb, but no login prompt (user icon + password field etc.).

The only error logged between sleep and wake is

```
com.apple.xpc.launchd[1] (com.w0lf.dblockinjector): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

plus

```
com.apple.xpc.launchd[1] (com.apple.qmaster.qmasterd): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

and an occasional

```
netbiosd[65689]: DEPRECATED USE in libdispatch client: Setting timer interval to 0 requests a 1ns timer, did you mean FOREVER (a one-shot timer)?
```

The only solution is a hard reboot. Waiting doesn't help. After reboot & login the first error above (com.w0lf.dblockinjector) still occurs every 10 seconds or so. Can't say if this wake/login error is related to DarkBoot, or even if the above errors have something to do with each other.

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/DarkBoot/issues/109
