### ISSUE TITLE
Problems resetting to default logo on 2018 rMBP with FileVault enabled

### ISSUE THREAD

**Issue by MrMage** [w0lfschild/DarkBoot#99]
Hi,

About two years ago I had used Dark Boot to enable a dark boot screen on my (back then) El Capitan Hackintosh. I have now used Migration Assistant to install that Hackintosh's config on my brand new 2018 rMBP, which has File Vault enabled (but I think this also happened before enabling FV).

At launch, the File Vault screen shows up in gray, but the Apple logo in the center of the screen is clearly off color for a few seconds (white with black background). During boot, the progress bar changes color from dark to bright. I have tried all boot screen color presets in Dark Boot and rebooted twice after each, to no effect.

After resetting the PRAM, my FileVault screen instead shows the default High Sierra background image (which happens to be my current desktop background) and the boot looks as it should (seamless transition to my desktop, with the background image present all the time). However, as soon as I reboot once more, I'm back to the grey screen with off-color Apple logo.

Do you have any suggestion on how to permanently reset to the MacBook's original default boot screen? Also, are there any steps besides deleting the application bundle to uninstall Dark Boot (e.g., any login items to remove)? (I don't care about leftover preferences in `~/Library`.)

Thanks in advance,
Daniel

**Comment by w0lfschild** [comment]
Delete these if they exists, then 2 reboots should be back to normal at least in terms of boot color.

`/Library/LaunchDaemons/com.dabrain13.darkboot.plist`
`/Library/LaunchDaemons/com.w0lf.dbcolor.plist`

**Comment by MrMage** [comment]
That worked, thanks a lot!
